version: '3'
services:
  mtcgdb:
    image: postgres
    container_name: mtcgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
